// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OwnedCollections;

namespace OwnedCollections.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20180829160903_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview1-35029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OwnedCollections.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("OwnedCollections.Parent", b =>
                {
                    b.OwnsMany("OwnedCollections.Child", "Children", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FirstName");

                            b1.Property<string>("LastName");

                            b1.Property<Guid>("ParentId");

                            b1.HasKey("Id");

                            b1.HasIndex("ParentId");

                            b1.ToTable("Child");

                            b1.HasOne("OwnedCollections.Parent")
                                .WithMany("Children")
                                .HasForeignKey("ParentId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
